name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:

  get:
    name: Get version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get versions
        id: version
        run: |
          next="v$(cat VERSION)"
          echo "next=$next" >> "$GITHUB_OUTPUT"

    outputs:
      next_version: ${{ steps.version.outputs.next }}

  tag:
    name: Tag
    needs: get
    uses: ./.github/workflows/tag-version.yml
    permissions:
      contents: write
    with:
      next_version: ${{ needs.get.outputs.next_version }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
